
# download fastq files from GEO using parallel-fastq-dump


rule fastq_dump:
    input:
        "sra_download.sh"
    envmodules:
	"parallel-fastq-dump/0.6.6-gimkl-2020a-Python-3.8.2"
    threads: 32
    shell:
        "bash {input}"
