
# download fastq files from GEO using parallel-fastq-dump


rule fastq_dump:
    input:
        "sra_download.sh"
    log:
        "/scale_wlg_persistent/filesets/project/uoa02869/colon_cancer_hic/raw_data/fastq/fastq_dump.log"
    envmodules:
	"parallel-fastq-dump/0.6.6-gimkl-2020a-Python-3.8.2"
    threads: 48
    resources:
        tmpdir="/scale_wlg_persistent/filesets/project/uoa02869/colon_cancer_hic/raw_data/fastq"
    shell:
        "bash {input}"
